/**
 * One-off golden-fixture generator (PROD-025 tooling, NOT shipped in the
 * package's test suite): builds the canonical derivation worlds through
 * the ENGINE (replay + validate) and the package derivation, and writes
 * the committed golden fixtures:
 *
 *  - `fixtures/wall-upgrade-boq-expected.json` — the GOLDEN generated BOQ
 *    of the wall-upgrade world (demolition → block wall → plaster);
 *  - `fixtures/two-pass-boq-expected.json` — the GOLDEN generated BOQ of
 *    the two-pass plaster world (merged line + modified contribution +
 *    stated uncertainties + conflict assumptions);
 *  - `fixtures/version-pair-expected.json` — the GOLDEN v1/v2 BOQ pair of
 *    the same solution + the deterministic version-pair delta.
 *
 * Run: cd packages/solution-boq && bun scripts/generate-golden.ts
 *
 * The committed fixtures are regenerated byte-identically by the same
 * command (pure deterministic computation — no clock, no randomness);
 * fixtures.test.ts asserts the in-memory reproduction matches the
 * committed bytes.
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { canonicalJsonStringify } from "@aise/shared-contracts";
import { deriveSolutionBoq, diffSolutionBoqs } from "../src/index";
import {
  twoPassWorld,
  versionPairWorld,
  wallUpgradeWorld,
} from "../src/testkit";

const FIXTURES = join(import.meta.dir, "..", "fixtures");

function writeGolden(name: string, value: unknown): void {
  writeFileSync(join(FIXTURES, name), canonicalJsonStringify(value));
  process.stdout.write(`wrote fixtures/${name}\n`);
}

/* 1. The wall-upgrade golden BOQ. */
const wallUpgrade = wallUpgradeWorld();
const wallUpgradeBoq = deriveSolutionBoq({
  version: wallUpgrade.version,
  snapshot: wallUpgrade.snapshot,
});
writeGolden("wall-upgrade-boq-expected.json", wallUpgradeBoq);

/* 2. The two-pass golden BOQ (merged line + uncertainty/conflict). */
const twoPass = twoPassWorld();
const twoPassBoq = deriveSolutionBoq({
  version: twoPass.version,
  snapshot: twoPass.snapshot,
});
writeGolden("two-pass-boq-expected.json", twoPassBoq);

/* 3. The version-pair golden (v1 + v2 BOQs + the delta). */
const pair = versionPairWorld();
const v1Boq = deriveSolutionBoq({ version: pair.v1.version, snapshot: pair.v1.snapshot });
const v2Boq = deriveSolutionBoq({ version: pair.v2.version, snapshot: pair.v2.snapshot });
const delta = diffSolutionBoqs(v1Boq, v2Boq);
writeGolden("version-pair-expected.json", {
  v1: v1Boq,
  v2: v2Boq,
  delta,
});

process.stdout.write("done.\n");
