/**
 * PROD-020 — the desktop shell's reproducible BUILD script.
 *
 * Bundles the thin Electron main entry (`src/shell/main.ts`) and the
 * adapter layer it drives into `dist/shell/main.js` with esbuild
 * (platform=node, `electron` and node builtins external — the platform
 * binary is a devDependency of THIS package only, never a root
 * dependency). Deterministic: no minification variance, no timestamps;
 * the same tree always produces the same bundle.
 *
 * Usage (in apps/desktop):  bun run build
 *
 * The web application the shell loads is built by ITS own workflow
 * (`cd apps/web && bun run build` — see README.md); this script builds
 * only the desktop shell.
 */

import { build } from "esbuild";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const PACKAGE_ROOT = resolve(import.meta.dir, "..");
const OUTDIR = join(PACKAGE_ROOT, "dist", "shell");

mkdirSync(OUTDIR, { recursive: true });

const result = await build({
  entryPoints: [join(PACKAGE_ROOT, "src", "shell", "main.ts")],
  outfile: join(OUTDIR, "main.js"),
  bundle: true,
  platform: "node",
  target: "node20",
  format: "esm",
  sourcemap: false,
  external: ["electron", "node:*", "fsevents"],
  logLevel: "info",
});

if (result.errors.length > 0) {
  process.exit(1);
}

// A deterministic marker of WHAT was built (source listing, not a clock).
const banner = [
  "// PROD-020 — AISE desktop shell bundle (generated by scripts/build.ts).",
  "// Entry: src/shell/main.ts — the thin platform layer over the adapter",
  "// layer (@aise/desktop). Rebuild with: bun run build",
].join("\n");

const bundled = readFileSync(join(OUTDIR, "main.js"), "utf8");
writeFileSync(join(OUTDIR, "main.js"), `${banner}\n${bundled}`);
