import { readFileSync } from "node:fs";
import { join } from "node:path";

/**
 * GBIM-003 — serves the committed spike evidence results (scorecard +
 * negative/discrimination checks) generated by
 * apps/spatial-studio-spike/src/server/run-checks.ts in the AISE clone.
 */
const RESULTS_PATH = join(
  process.cwd(),
  "AISE",
  "docs",
  "productization-evidence",
  "GBIM-003",
  "results",
  "spike-results.json",
);

export async function GET(): Promise<Response> {
  try {
    const raw = readFileSync(RESULTS_PATH, "utf8");
    return new Response(raw, { headers: { "content-type": "application/json" } });
  } catch {
    return Response.json(
      {
        generatedAt: "unavailable",
        fixtureSha256: "-",
        checks: [
          {
            id: "evidence-load",
            title: "evidence results JSON",
            verdict: "PARTIAL",
            evidence:
              "results/spike-results.json was not found on this host — generate it with: bun apps/spatial-studio-spike/src/server/run-checks.ts (inside the AISE clone)",
          },
        ],
        scorecard: [],
      },
      { status: 200 },
    );
  }
}
